### ISSUE TITLE
Optimize using simplified gzip function

### ISSUE THREAD

**Issue by GretaCB** [mapbox/gzip-hpp#11]
Per chat with @joto , we learned that gzip lib has [another API](http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/zlib-gzwrite-1.html) that takes the original filesize. [See example in libosmium](https://github.com/osmcode/libosmium/blob/c0597584f5a81aa303811c5b1d1587f799ca2339/include/osmium/io/gzip_compression.hpp#L127). This could help with performance in gzip-hpp to avoid [constantly resizing](https://github.com/mapbox/gzip-hpp/blob/master/include/gzip/decompress.hpp#L43-L56) the memory allocation.

This would mean grabbing the original filesize via zlib's [`ISIZE` flag](https://github.com/madler/zlib/blob/master/doc/rfc1952.txt#L427-L429) stored in the header.

cc @springmeyer

**Comment by GretaCB** [comment]
Per investigation with @springmeyer , we discovered that there [isnt a reliable source](https://stackoverflow.com/a/9213826) for original uncompressed size. 

When decompressing in gzip-hpp, we wont always have a way of knowing the original buffer size. Therefore, we wouldnt be able to use zlib's uncompress function, which requires passing the original size as a param.

Future note:
- We may want to bench both APIs side by side to see if there is major performance benefit between our current manual process and [zlib's uncompress function](https://github.com/madler/zlib/blob/master/uncompr.c)
- If there is a major performance benefit to using the zlib's uncompress function, we _could_ add an option to include original size. We would then need to come up with a fancy way to get the original buffer size via s3 header or something.

**Comment by springmeyer** [comment]
> Per investigation with @springmeyer , we discovered that there isnt a reliable source for original uncompressed size.

I noticed that libdeflate has a sample program that looks intended to parse out the originall uncompressed size: https://github.com/ebiggers/libdeflate/blob/99d6e72b896f394ae3b3466e2ac7e7640e7394a9/programs/gzip.c#L201. But I'm still trusting the [zlib author that this is not robust enough to be viable](https://stackoverflow.com/questions/9209138/uncompressed-file-size-using-zlibs-gzip-file-access-function/9213826#9213826)

**Comment by springmeyer** [comment]
> But I'm still trusting the zlib author that this is not robust enough to be viable

Found this to be the case. The `load_u32_gzip` in libdeflate fails to detect the right size (rather returning some massive number, which is dangerous for memory allocation). So, while it would be ideal to know this value beforehand, it appears not possible and therefore this ticket is not actionable. In the future we could consider offering an API signature that supports when the user knows the uncompressed size somehow (like when they are decoding a file format that embeds it), but I don't this we should provide this now: it would be a security vulnerability to expose.
