### ISSUE TITLE
Tag v1.0.0 / Package in Mason

### ISSUE THREAD

**Issue by springmeyer** [mapbox/gzip-hpp#12]
Once @GretaCB feels this library is ready for release, let's plan to tag as v1.0.0 and package in mason.

The general flow will be:

 - Tag here: `git tag v1.0.0 -a -m "Tagging gzip-hpp v1.0.0"`
 - Push the tag: `git push --tags`
 - Then head over to mason to:
   - Create a new branch
   - Create a `gzip` package
   - Push the branch
   - Test a build with `./mason trigger gzip 1.0.0`

I've pushed some updated docs on mason packaging at https://github.com/mapbox/mason/pull/478.

/cc @GretaCB

**Comment by GretaCB** [comment]
PR over at https://github.com/mapbox/mason/pull/480

**Comment by GretaCB** [comment]
v1.0.0 published per https://github.com/mapbox/mason/pull/605.
