### ISSUE TITLE
Where did this implementation originally come from?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/gzip-hpp#14]
This project exists, in part, to stop the dangerous practice of copying code around without properly understanding what it does and without there being a clear lineage of bug fixes and docs.

So, we are working on starting off on the right foot in this repo / fixing our colored past. But the question has come up during the vetting of the code of: "where did this come from and why was this decision made?".

I spent some time trying to figure out the history. We know that proximately we copied the code from mapnik-vector-tile to get this project started, but where did that code come from? Well, if you search on github for `while (inflate_s.avail_out == 0)` (which is a pretty unique line) we get a bunch of hits for the same code copied around: https://github.com/search?q=while+%28inflate_s.avail_out+%3D%3D+0%29&type=Code&utf8=%E2%9C%93. In looking at that I think the first to come along was https://github.com/kkaefer/DEPRECATED-node-zlib from @kkaefer. So I think that is the origination of the code that `mapnik-vector-tile` has been using. And the [history of commits in that repo](https://github.com/kkaefer/DEPRECATED-node-zlib/commits/d5fad4d243182eabc9a404d1a4c13e55bf567f8f/src/node-zlib.cc) show some of the reasons for changes in the code (like the addition of handling of `Z_BUF_ERROR` in https://github.com/kkaefer/DEPRECATED-node-zlib/commit/523477f17f397e8e455b19e4613204e5efcb8786#diff-1edfe6d0b0a3a9c5bcbb3ba0e11144a9).

**Comment by springmeyer** [comment]
Looks like the `node-zlib` code likely was adapted from https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/examples/zpipe.c

**Comment by kkaefer** [comment]
I wrote this code based on the API/workflow description in the [zlib manual](https://zlib.net/manual.html) and the [usage example](https://zlib.net/zlib_how.html) (which is very similar to the file you linked), but I implemented a few things differently. In any case, the howto code is in the public domain.

**Comment by springmeyer** [comment]
@kkaefer - thank you 🙏
