### ISSUE TITLE
Streaming vs strings

### ISSUE THREAD

**Issue by flippmoke** [mapbox/gzip-hpp#24]
As a general design we should likely be encouraging the use of streaming operators with zlib which is a streaming algorithm. There is not a simple way to make or use a streaming C++ operation here with this current design. I think this is a mistake as I/O operations will almost always be slower then any gzip decompression or compression. I think basic tools to operate on existing buffers is great, but we should be focused on making our operations more based on streams for performance reasons.

**Comment by springmeyer** [comment]
per voice, we don't have a usecase for streaming in downstream code we're targeting (node-mapnik, vtquery, vtvalidate). So, this does not feel actionable to me. Closing. Please re-open if there is a concrete usecase that is or becomes clearer.
