### ISSUE TITLE
Write section about how to detect if a file is compressed?

### ISSUE THREAD

**Issue by mapsam** [mapbox/gzip-hpp#3]
It'd be great to include an example section (or perhaps even a method?) about how to check if a string or buffer _is_ compressed. Perhaps `gzip::uncompress` does this internally?

cc @GretaCB @springmeyer

**Comment by GretaCB** [comment]
@mapsam Just added an example and test in the [`update-readme` PR](https://github.com/mapbox/gzip-hpp/pull/1). This should cover it?

**Comment by mapsam** [comment]
@GretaCB this is really great - thank you!
