### ISSUE TITLE
Travis temporarily broken

### ISSUE THREAD

**Issue by springmeyer** [mapbox/gzip-hpp#33]
I noticed this repo is currently in an odd state due to https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org. When trying to enable it on `https://travis-ci.com/profile/mapbox` I see:

![screen shot 2018-09-27 at 10 46 39 am](https://user-images.githubusercontent.com/20300/46164394-bc71ba00-c242-11e8-9907-4d9fe09119b3.png)

@artemp until this is fixed please ensure your tests are passing locally at https://github.com/mapbox/gzip-hpp/pull/25 and ensure you get another reviewer to confirm as well.

/cc @mapsam for visibility

**Comment by agius** [comment]
I have emailed Travis support about this issue - will follow up here with discussion & results.

**Comment by springmeyer** [comment]
Thank you @agius.

**Comment by springmeyer** [comment]
Noticed that as of today `.com` is still saying "it is not migrated" and ".org" is disabled. But I tried re-enabling and now `.org` is working again. Yesterday `.org` was not responding. Interesting....

**Comment by agius** [comment]
Looks like checks are re-enabled & working! 🎉 Good to close this out?

<img width="775" alt="screen shot 2018-09-28 at 1 20 17 pm" src="https://user-images.githubusercontent.com/162151/46231580-527c1200-c321-11e8-9199-4e1868328bf7.png">

**Comment by springmeyer** [comment]
👍 yes, good to close out. Thank you!
