### ISSUE TITLE
Move to single compress API

### ISSUE THREAD

**Issue by GretaCB** [mapbox/gzip-hpp#4]
Uncovered that the `std::string` compress method is [causing unintentional behaviour](https://github.com/mapbox/gzip-hpp/pull/1#issuecomment-326078576) that could affect performance.

What happens is that when you fail to pass size to the `const char *` pointer method, it dispatches to the other `std::string` function, creates a `std::string` implicitly, and the size of that is used. So things work right, just not quite as you would hope, and an extra string copy is created that we do not want.

Per chat with @artemp re: strong types, we may want to be more explicit here. When performance and reliability are critical, then requiring more explicit types is well worth it since they can guarantee correct code.

### Next Actions
- See https://github.com/mapbox/gzip-hpp/pull/1#issuecomment-326078576

cc @mapbox/core-tech

**Comment by springmeyer** [comment]
@GretaCB I've added the strong types doc for reference here: https://github.com/mapbox/cpp/pull/34.

In this case performance is absolutely critical so I'm hesitant to use strong types. Not that I have any proof they will add overhead, but the current implementation could result in a copy if the copy constructor is used: https://github.com/mapbox/cpp/pull/34/files#diff-e59ffafe076d2f0525d7d97b7993635bR144.

So, my feeling is that we should simply remove the `compress(std::string const& ...` function signature. This will have the same result (trigging compile error if `size` is not correctly passed) without any chance of performance overhead.

**Comment by GretaCB** [comment]
Implemented per https://github.com/mapbox/gzip-hpp/pull/5. Closing.
